### PR TITLE
Broken curl command

### PR DESCRIPTION
**Pull request by lholznagel**
When I tried to run the curl command it always said that no URL is specified. With the curl like I changed it, it works. Also a step less :D

### CODE REVIEW

**Comment by ramitsurana** [comment]
Cool.Thanks @lholznagel for the PR ! For the future I was thinking about asking the users to directly use one command to download the binary file from releases and mv it to there local path.Similar to the one done by kubectl and minikube. Somewhat like 

```
curl -Lo turbo https://github.com/ramitsurana/turbo/releases/download/v0.2/turbo && chmod +x turbo && sudo mv turbo /usr/local/bin
```

**Comment by lholznagel** [comment]
Okay, sounds good. Do you know if it is possible to change the `v0.2` to something like `latest`? Will be easier and you cannot forget to update it in the readme.

**Comment by ramitsurana** [comment]
Nope I think it's better we  leave the releases to something like that until its we release a stable release. I think a better approach to that would be by asking users to view the latest releases themselves in the readme section,and instructions of using turbo on the releases will shown as it is.Somewhat like these guys have done https://github.com/kubernetes/minikube/releases .This will give the users some freedom to choose between older versions if they don't like the latest update.What do you say ?

**Comment by lholznagel** [comment]
Hm, good point with checking out older releases. 
How about to add something that says: `If you want to check out an older version, you can replace the latest with vx.x.x` (x = version)

**Pull request merged**
